[package]
name = "permitlist_mismatch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitm = "0.5.2"
bitnuc = "0.4.0"
bitnuc-mismatch = "0.1.2"
clap = { version = "4.5.54", features = ["derive"] }
rustc-hash = "2.1.1"
serde_json = "1.0.149"
zip = "7.2.0"
